version: '3.9'

services: 
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - postgres
    ports:
      - 4000:4000
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public

volumes:
  db:

