version: '3.3'

services: 
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - postgres
    ports:
      - 4000:4000
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse_proxy
    depends_on:
        - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/ssl/cert.pem:/etc/ssl/cert.pem
      - /etc/nginx/ssl/key.pem:/etc/ssl/key.pem
    ports:
      - 80:80
      - 443:443

volumes:
  db: